"""Add duration to Semester table

Revision ID: 22681c4a3f77
Revises: 4f889204347a
Create Date: 2024-07-25 09:22:44.181032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '22681c4a3f77'
down_revision: Union[str, None] = '4f889204347a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semester', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semester', 'duration')
    op.create_table('programmes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('programmename', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('semesters', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignableIntake', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='programmes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_programmes_programmename', 'programmes', ['programmename'], unique=False)
    op.create_index('ix_programmes_id', 'programmes', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_admins_id', 'admins', ['id'], unique=False)
    op.create_index('ix_admins_email', 'admins', ['email'], unique=True)
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coursename', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('assignableIntake', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_course_id', 'course', ['id'], unique=False)
    op.create_table('schedulers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hashed_password', mysql.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_schedulers_id', 'schedulers', ['id'], unique=False)
    op.create_index('ix_schedulers_email', 'schedulers', ['email'], unique=True)
    op.create_table('majors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('majorname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('programme_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name='majors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_majors_majorname', 'majors', ['majorname'], unique=False)
    op.create_index('ix_majors_id', 'majors', ['id'], unique=False)
    # ### end Alembic commands ###
