"""empty message

Revision ID: 717dc1a6e60c
Revises: 
Create Date: 2024-07-11 08:27:30.023785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '717dc1a6e60c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('persons')
    op.drop_table('posts')
    op.add_column('intake', sa.Column('orientation', sa.Integer(), nullable=False))
    op.add_column('intake', sa.Column('startdate', sa.Date(), nullable=False))
    op.add_column('intake', sa.Column('enddate', sa.Date(), nullable=False))
    op.add_column('intake', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('intake', sa.Column('code', sa.String(length=50), nullable=True))
    op.alter_column('intake', 'groupid',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('intake', 'content')
    op.drop_column('intake', 'intakename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake', sa.Column('intakename', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('intake', sa.Column('content', mysql.VARCHAR(length=50), nullable=True))
    op.alter_column('intake', 'groupid',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('intake', 'code')
    op.drop_column('intake', 'duration')
    op.drop_column('intake', 'enddate')
    op.drop_column('intake', 'startdate')
    op.drop_column('intake', 'orientation')
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('persons',
    sa.Column('PersonID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('LastName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FirstName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=255), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
