"""empty message

Revision ID: 88ef1cc2ca44
Revises: 481e215936ad
Create Date: 2024-07-17 10:46:24.089489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88ef1cc2ca44'
down_revision: Union[str, None] = '481e215936ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_id', table_name='course')
    op.drop_table('course')
    op.drop_index('ix_majors_id', table_name='majors')
    op.drop_index('ix_majors_majorname', table_name='majors')
    op.drop_table('majors')
    op.drop_index('ix_programmes_id', table_name='programmes')
    op.drop_index('ix_programmes_programmename', table_name='programmes')
    op.drop_table('programmes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programmes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('programmename', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('semesters', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='programmes_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_programmes_programmename', 'programmes', ['programmename'], unique=False)
    op.create_index('ix_programmes_id', 'programmes', ['id'], unique=False)
    op.create_table('majors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('majorname', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('programme_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], name='majors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_majors_majorname', 'majors', ['majorname'], unique=False)
    op.create_index('ix_majors_id', 'majors', ['id'], unique=False)
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coursename', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_course_id', 'course', ['id'], unique=False)
    # ### end Alembic commands ###
